
MOCK_MOONDREAM_MODEL_DATA = {
    "details": {
        "parent_model": "",
        "format": "gguf",
        "family": "phi2",
        "families": ["phi2", "clip"],
        "parameter_size": "1B",
        "quantization_level": "Q4_0",
    },
    "model_info": {
        "general.architecture": "phi2",
        "general.file_type": 2,
        "general.parameter_count": 1418270720,
        "general.quantization_version": 2,
        "phi2.attention.head_count": 32,
        "phi2.attention.head_count_kv": 32,
        "phi2.attention.layer_norm_epsilon": 0.00001,
        "phi2.block_count": 24,
        "phi2.context_length": 2048,
        "phi2.embedding_length": 2048,
        "phi2.feed_forward_length": 8192,
        "phi2.rope.dimension_count": 32,
        "tokenizer.ggml.add_bos_token": False,
        "tokenizer.ggml.bos_token_id": 50256,
        "tokenizer.ggml.eos_token_id": 50256,
        "tokenizer.ggml.merges": None,
        "tokenizer.ggml.model": "gpt2",
        "tokenizer.ggml.token_type": None,
        "tokenizer.ggml.tokens": None,
        "tokenizer.ggml.unknown_token_id": 50256,
    },
    "projector_info": {
        "clip.has_llava_projector": True,
        "clip.has_text_encoder": False,
        "clip.has_vision_encoder": True,
        "clip.projector_type": "mlp",
        "clip.use_gelu": True,
        "clip.vision.attention.head_count": 16,
        "clip.vision.attention.layer_norm_epsilon": 0.000001,
        "clip.vision.block_count": 28,
        "clip.vision.embedding_length": 1152,
        "clip.vision.feed_forward_length": 4304,
        "clip.vision.image_mean": [0.5, 0.5, 0.5],
        "clip.vision.image_size": 378,
        "clip.vision.image_std": [0.5, 0.5, 0.5],
        "clip.vision.patch_size": 14,
        "clip.vision.projection_dim": 2048,
        "general.architecture": "clip",
        "general.description": "image encoder for vikhyatk/moondream2",
        "general.file_type": 1,
        "general.name": "vikhyatk/moondream2",
        "general.parameter_count": 454451392,
    },
    "modified_at": "2025-01-28T11:12:41.477935053Z",
}
